Debug Boot (DebugOpeningState)
HackerN64/HackerOoT pull request #136
Opened 2024-06-16 00:57 UTC by Trueffeloot

This PR adds my Debug Boot which I previously shared on discord: https://discord.com/channels/879505781916053544/996101154238894110/1243562597006053436

I had to change a lot of stuff in the macros in order to get this working. It uses the map select macro together with the map select because the debug boot and the map select work together in a few ways. One should not be without the other based on this code.
I couldn't find any bugs but I didn't test the debug boot that much in the end if I'm being honest. If bugs appear, reach out to me on discord

2024-06-22 01:46 UTC, Yanis42 requested changes
imo this entire thing should be named "Boot Menu" instead of having inconsistent names (currently there's "boot menu", "debug boot" and "debug opening")

2024-06-22 01:46 UTC, Yanis42 commented on Makefile
> +CFLAGS_IDO += -DPACKAGE_AUTHOR='$(PACKAGE_AUTHOR)' -DCOMPRESS_$(COMPRESSION_TYPE)=1
this is confusing me a lot, why not just do ``-DPACKAGE_VERSION='$(PACKAGE_VERSION)' -DPACKAGE_NAME='$(PACKAGE_NAME)' -DPACKAGE_COMMIT_AUTHOR='$(PACKAGE_COMMIT_AUTHOR)' -DPACKAGE_AUTHOR='$(PACKAGE_AUTHOR)' -DCOMPRESS_$(COMPRESSION_TYPE)=1``?

2024-06-22 01:46 UTC, Yanis42 commented on include/config/config_safeguards.h
> +#if (BOOT_TO_DEBUG_OPENING || MAP_SELECT_ON_FILE_1) && !ENABLE_MAP_SELECT
with this change if you set ``BOOT_TO_MAP_SELECT`` to true it won't enable the map select automatically anymore

2024-06-22 01:46 UTC, Yanis42 commented on include/tables/gamestate_table.h
> +#if IS_MAP_SELECT_ENABLED
did you meant to use ``IS_DEBUG_BOOT_ENABLED``?

2024-06-22 01:46 UTC, Yanis42 commented on include/variables.h
> +#if IS_MAP_SELECT_ENABLED
``IS_DEBUG_BOOT_ENABLED``? also some of these might be used on the rotating n64 logo screen (like the build author and the date)

2024-06-22 01:46 UTC, Yanis42 commented on include/z64.h
> +#if IS_MAP_SELECT_ENABLED
``IS_DEBUG_BOOT_ENABLED``? also it's probably worth to move the structs/functions declarations to a dedicated header

2024-06-22 01:46 UTC, Yanis42 commented on spec
> +#if IS_MAP_SELECT_ENABLED
``IS_DEBUG_BOOT_ENABLED``?

2024-06-22 01:46 UTC, Yanis42 commented on src/boot/build.c
> +#if (defined IS_MAP_SELECT_ENABLED && defined PACKAGE_AUTHOR)
same comment about ``IS_DEBUG_BOOT_ENABLED`` and the n64 logo gamestate

2024-06-22 01:46 UTC, Yanis42 commented on src/overlays/gamestates/ovl_debug_opening/debug_opening.h
> +#endif
missing newline here

2024-06-22 01:46 UTC, Yanis42 commented on src/overlays/gamestates/ovl_debug_opening/debug_opening.h
why not declaring the struct from z64.h here? same for the functions you added in functions.h

2024-06-22 01:46 UTC, Yanis42 commented on src/overlays/gamestates/ovl_debug_opening/z_debug_opening.c
> +#if IS_MAP_SELECT_ENABLED
``IS_DEBUG_BOOT_ENABLED``?

2024-06-22 01:46 UTC, Yanis42 commented on src/overlays/gamestates/ovl_debug_opening/z_debug_opening.c
> +    gSaveContext.save.dayTime = CLOCK_TIME(12, 0);
this should use ``BOOT_TIME`` imo

2024-06-22 01:46 UTC, Yanis42 commented on src/overlays/gamestates/ovl_debug_opening/z_debug_opening.c
> +    gSaveContext.seqId = (u8)NA_BGM_DISABLED;
why casting to u8? (same for the other ones, I'm curious)

2024-06-22 01:46 UTC, Yanis42 commented on src/overlays/gamestates/ovl_debug_opening/z_debug_opening.c
> +        .name = "Init Defined Scene",
I think instead of "Init XXX" we should use like "Go to XXX" or "Execute XXX"

2024-06-22 01:46 UTC, Yanis42 commented on src/overlays/gamestates/ovl_debug_opening/z_debug_opening.c
> +        Audio_PlaySfxGeneral(NA_SE_IT_SWORD_IMPACT, &gSfxDefaultPos, 4, &gSfxDefaultFreqAndVolScale,
just a detail but I think it'd be nice if it was using the same sfx the map select is using when going to the next line

2024-06-22 01:46 UTC, Yanis42 commented on src/overlays/gamestates/ovl_debug_opening/z_debug_opening.c
> +#define EXPAND_AND_STRINGIFY(s) STRINGIFY(s)
I wonder if it's worth moving these to macros.h, so it's not defined twice (the other one being in build.c I think?)

2024-06-22 01:46 UTC, Yanis42 commented on src/overlays/gamestates/ovl_debug_opening/z_debug_opening.c
> +    } else if (CHECK_BTN_ANY(this->state.input[0].press.button, BTN_L) && this->page != OPTIONS_PAGE) {
I think it should be using ``BTN_Z`` because if feels more natural than L with an n64 controller and it makes it less weird on a gamecube controller

2024-06-22 01:46 UTC, Yanis42 commented on src/overlays/gamestates/ovl_select/z_select.c
> +#if BOOT_TO_DEBUG_OPENING
what if I wanna use boot to map select instead of the boot menu? I'm a bit confused by this

2024-06-22 01:46 UTC, Yanis42 commented on src/overlays/gamestates/ovl_title/z_title.c
> -            GfxPrint_Printf(printer, "Powered by F3DEX3!");
I think you should add the rainbow "powered by f3dex3" print to the boot menu

2024-06-22 01:46 UTC, Yanis42 commented on src/overlays/gamestates/ovl_title/z_title.c
> +#if ENABLE_HACKER_DEBUG
why not using ``IS_DEBUG`` here?

2024-06-22 01:46 UTC, Yanis42 commented on src/overlays/gamestates/ovl_title/z_title.c
> +#if BOOT_TO_SCENE
I'm a bit confused about why this is needed, I assume it's supposed to replace the stuff you removed from ``TitleSetup_SetupTitleScreen``? in this case why not booting to the boot menu for every debug cases and determine if it should show the menu or directly jump to the execution process based on which setting you're using?

2024-06-22 01:46 UTC, Yanis42 commented on src/overlays/gamestates/ovl_debug_opening/z_debug_opening.c
> +    GfxPrint_Printf(printer, "Zelda Debug Boot");
I think this should be named "HackerOoT Boot Menu"

2024-06-22 01:48 UTC, Yanis42 commented
oh also something I'd like to have is going back to the first page if you press "R" on the last one and vice versa

2024-12-31 17:02 UTC, Yanis002 commented
if that's fine with you I can push commits to your branch and merge this once my review is addressed

2025-01-01 10:48 UTC, Trueffeloot commented
> if that's fine with you I can push commits to your branch and merge this once my review is addressed

That would be awesome yanis! I'm sorry I didn't have the time or interest to work on decomp and modding for a while. Thank you for your help!

2025-01-02 02:59 UTC, Yanis002 approved these changes

2025-01-02 17:14 UTC, merged