initial virtual console support
HackerN64/HackerOoT pull request #26
Opened 2022-12-05 03:05 UTC by ariahiro64

to build a wad you must place a us wad named ``basewad.wad``
build your rom like normal
the rom will automatically compress in ``lzo`` format
after it compresses now do ``make wad``
profit

2022-12-05 10:55 UTC, Yanis42 requested changes
your branch is really weird, there's a lot of unwanted changes, I feel like you made a branch from your mod branch lol

but anyway I made some comments, fix your branch first and review next, also for the spec file note that I have also [a spec with compress symbols in it](https://github.com/Yanis42/oot/blob/compression/spec), idk if you took this for the PR or not but might be worth to compare to see if anything's missing

2022-12-05 10:55 UTC, Yanis42 commented on Makefile
> +	$(RM) -rf vc/wadextract vc/common-key.bin
also for the rom header you can just edit ``rom_header.s`` with an ifdef and you add a define in the compiler flags if you use ``make wad``, I can try this and make a PR if you want

```c
.word  0x0000004E               /* Cartridge */
.ascii "ZL"                     /* Cartridge ID */
.ascii "E"                      /* Region */
```
for instance this is "NZLE", you just need to replace the 4E by the ascii char for 'C' (which is 0x43)

2022-12-05 10:55 UTC, Yanis42 commented on Makefile
> +#	python3 extract_assets.py -j$(N_THREADS)
probably something you forgot to uncomment lol

2022-12-05 10:57 UTC, Yanis42 commented
I think I'm gonna take the changes, apply my comments and make a PR to your branch, I feel like it's easier this way to fix your branch

2022-12-06 05:34 UTC, ariahiro64 commented on Makefile
> +build/src/overlays/actors/ovl_Bg_Mori_Hineri/%.o: OPTFLAGS := -O0
this is to prevent the rotating room in forest temple from crashing on vc

2022-12-06 05:35 UTC, ariahiro64 commented on Makefile
> +  OPTFLAGS := -O2 -ffast-math -fno-unsafe-math-optimizations
was changed to prevent a load of actors from crashing

2022-12-06 05:36 UTC, ariahiro64 commented on Makefile
> +  CFLAGS += -G 0 -nostdinc $(INC) -march=vr4300 -mfix4300 -mabi=32 -mno-abicalls -mdivide-breaks -fno-zero-initialized-in-bss -fno-toplevel-reorder -ffreestanding -fno-common -fno-merge-constants -mn
more crash prevention on vc

2022-12-09 01:42 UTC, ariahiro64 commented
Most changes should be there. I have also changed -Os to -O2 as this fixes alot of crashes on vc. It should also work on real hardware.

2022-12-09 05:06 UTC, ariahiro64 commented
i found the culprit. it was the effect spawner.

2022-12-10 08:55 UTC, closed without merging

2022-12-10 08:55 UTC, ariahiro64 commented
this pull request is too massive ill reopen it with only required changes