Pause delay fix that works on console
HackerN64/HackerOOT pull request #4
Opened 2022-08-06 12:01 UTC by AriaHiro64

Have no idea why this code is called but it does nothing but lag emulators. Removing it is a slight speed boost on console and a major on emulator.

2022-08-06 16:42 UTC, Yanis42 commented
PR #2 has a fix for the pause menu I believe

2022-08-06 19:26 UTC, Recardo-7 commented
> PR #2 has a fix for the pause menu I believe

It fixed the crash that sometimes occurs when pausing. Didn't speed it up.

2022-08-07 01:59 UTC, Zelllll requested changes

2022-08-07 01:59 UTC, Zelllll commented on src/code/PreRender.c
> -                if (a != 8) {
If you look closely this isn't really the best way to do this. You removed the part of the loop that is actually doing something, and the rest of this function is now completely useless. You can just never call `PreRender_Calc` and remove this function and any other functions that it calls.

2022-08-07 20:16 UTC, AriaHiro64 commented
closing this for now because someone else has already made a pull request with it and i didnt realize it

2022-08-07 20:19 UTC, Recardo-7 commented
> 

#2 just fixed a crash that happens when pausing with the minimap open. It **did not** remove this function to speed up pausing.

2022-08-07 20:21 UTC, AriaHiro64 commented
actally ill keep it open just incase im doing somthing different

2022-08-09 23:04 UTC, AriaHiro64 commented
Rebased and did suggested changes so review when you can.

2022-09-04 16:55 UTC, Yanis42 commented
I'm worried about something I need to try myself about this PR, I'll review it once I tried

2022-09-04 17:38 UTC, Yanis42 approved these changes
Works on N64, my concern was about frame advancing the game using the pause menu, which can be really important sometimes if you wanna be the very best (like no one ever was)

2022-09-18 17:56 UTC, Zelllll commented on src/code/z_play.c
>                  Sched_FlushTaskQueue();
I believe you can remove this line too.

2022-09-18 17:56 UTC, Zelllll commented on src/overlays/misc/ovl_kaleido_scope/z_kaleido_scope_PAL.c
> -void KaleidoScope_ProcessPlayerPreRender(void) {
Removing this here isn't entirely correct since it also calls the destroy function.

2022-11-27 04:25 UTC, closed without merging