Widescreen minimaps
HackerN64/HackerOoT pull request #52
Opened 2023-04-24 15:51 UTC by ariahiro64

Fixes problems with the minimap's compass positions being wrong in game.

2023-09-03 13:09 UTC, Yanis42 requested changes
delete the hackeroot.ram file then I'll merge this peepoHappy

2023-09-05 00:23 UTC, ariahiro64 commented
should be good

2023-09-05 05:34 UTC, ariahiro64 commented
dont merge yet

2025-11-04 20:23 UTC, Yanis002 commented
closing for inactivity, feel free to open again once it's updated!

2025-11-04 20:23 UTC, closed without merging